// This file is generated by generate-std.joke script. Do not edit manually!

package base64

import (
	. "github.com/lab47/lace/core"
)

var __decode_string__P ProcFn = __decode_string_
var decode_string_ Proc = Proc{Fn: __decode_string__P, Name: "decode_string_", Package: "std/base64"}

func __decode_string_(_env *Env, _args []Object) (Object, error) {
	_c := len(_args)
	switch {
	case _c == 1:
		var err error
		s, err := ExtractString(_env, _args, 0)
		if err != nil {
			return nil, err
		}
		_res, err := decodeString(s)
		return MakeString(_res), err

	default:
		return nil, ErrorArity(_env, _c)
	}
}

var __encode_string__P ProcFn = __encode_string_
var encode_string_ Proc = Proc{Fn: __encode_string__P, Name: "encode_string_", Package: "std/base64"}

func __encode_string_(_env *Env, _args []Object) (Object, error) {
	_c := len(_args)
	switch {
	case _c == 1:
		var err error
		s, err := ExtractString(_env, _args, 0)
		if err != nil {
			return nil, err
		}
		_res, err := encodeString(s)
		return MakeString(_res), err

	default:
		return nil, ErrorArity(_env, _c)
	}
}

func Init() {

	InternsOrThunks()
}

var base64Namespace = GLOBAL_ENV.EnsureNamespace(MakeSymbol("lace.base64"))

func init() {
	base64Namespace.Lazy = Init
}
