// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_better_cond_data.data
var better_condData []byte

func better_condSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.better-cond"))
	return processInEnvInNS(env, ns, better_condData)
}

func init() {
	builtinNSSetup["lace.better-cond"] = better_condSetup
}



