// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_core_data.data
var coreData []byte

func coreSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.core"))
	return processInEnvInNS(env, ns, coreData)
}

func init() {
	builtinNSSetup["lace.core"] = coreSetup
}



