// Generated by gen_data. Don't modify manually!

package core

func init() {
	coreNamespaces = []string{
		"lace.template",
		"lace.tools.cli",
		"lace.pprint",
		"lace.better-cond",
		"lace.core",
		"lace.reflect",
		"lace.repl",
		"lace.walk",
		"lace.test",
		"lace.set",
		"lace.time",
	}
}
