// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_hiccup_data.data
var hiccupData []byte

func hiccupSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.hiccup"))
	return processInEnvInNS(env, ns, hiccupData)
}

func init() {
	builtinNSSetup["lace.hiccup"] = hiccupSetup
}



