// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data

//
package core

import "encoding/base64"
import _ "embed"

//go:embed a_pprint_data.data
var pprintData []byte

func pprintSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.pprint"))
	raw, err := base64.StdEncoding.AppendDecode(nil, pprintData)
	if err != nil {
		return err
	}
	return processInEnvInNS(env, ns, raw)
}

func init() {
	builtinNSSetup["lace.pprint"] = pprintSetup
}
