// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_pprint_data.data
var pprintData []byte

func pprintSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.pprint"))
	return processInEnvInNS(env, ns, pprintData)
}

func init() {
	builtinNSSetup["lace.pprint"] = pprintSetup
}



