// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_reflect_data.data
var reflectData []byte

func reflectSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.reflect"))
	return processInEnvInNS(env, ns, reflectData)
}

func init() {
	builtinNSSetup["lace.reflect"] = reflectSetup
}



