// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_repl_data.data
var replData []byte

func replSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.repl"))
	return processInEnvInNS(env, ns, replData)
}

func init() {
	builtinNSSetup["lace.repl"] = replSetup
}



