// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data

//
package core

import "encoding/base64"
import _ "embed"

//go:embed a_repl_data.data
var replData []byte

func replSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.repl"))
	raw, err := base64.StdEncoding.AppendDecode(nil, replData)
	if err != nil {
		return err
	}
	return processInEnvInNS(env, ns, raw)
}

func init() {
	builtinNSSetup["lace.repl"] = replSetup
}
