// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_set_data.data
var setData []byte

func setSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.set"))
	return processInEnvInNS(env, ns, setData)
}

func init() {
	builtinNSSetup["lace.set"] = setSetup
}



