// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data

//
package core

import "encoding/base64"
import _ "embed"

//go:embed a_test_data.data
var testData []byte

func testSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.test"))
	raw, err := base64.StdEncoding.AppendDecode(nil, testData)
	if err != nil {
		return err
	}
	return processInEnvInNS(env, ns, raw)
}

func init() {
	builtinNSSetup["lace.test"] = testSetup
}
