// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_template_data.data
var templateData []byte

func templateSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.template"))
	return processInEnvInNS(env, ns, templateData)
}

func init() {
	builtinNSSetup["lace.template"] = templateSetup
}



