// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data

//
package core

import "encoding/base64"
import _ "embed"

//go:embed a_template_data.data
var templateData []byte

func templateSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.template"))
	raw, err := base64.StdEncoding.AppendDecode(nil, templateData)
	if err != nil {
		return err
	}
	return processInEnvInNS(env, ns, raw)
}

func init() {
	builtinNSSetup["lace.template"] = templateSetup
}
