// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data

//
package core

import "encoding/base64"
import _ "embed"

//go:embed a_time_data.data
var timeData []byte

func timeSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.time"))
	raw, err := base64.StdEncoding.AppendDecode(nil, timeData)
	if err != nil {
		return err
	}
	return processInEnvInNS(env, ns, raw)
}

func init() {
	builtinNSSetup["lace.time"] = timeSetup
}
