// Generated by gen_data. Don't modify manually!

//go:build !gen_data
// +build !gen_data
package core

import _ "embed"

//go:embed a_tools_cli_data.data
var tools_cliData []byte

func tools_cliSetup(env *Env) error {
	ns := env.EnsureNamespace(MakeSymbol("lace.tools.cli"))
	return processInEnvInNS(env, ns, tools_cliData)
}

func init() {
	builtinNSSetup["lace.tools.cli"] = tools_cliSetup
}



