// Code generated by "stringer -type OpCode"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Noop-0]
	_ = x[Pop-1]
	_ = x[Dup-2]
	_ = x[Jump-3]
	_ = x[JumpIfTrue-4]
	_ = x[JumpIfFalse-5]
	_ = x[ResolveVar-6]
	_ = x[SetMacro-7]
	_ = x[GetBinding-8]
	_ = x[GetUpval-9]
	_ = x[SetUpval-10]
	_ = x[PushLiteral-11]
	_ = x[MakeVector-12]
	_ = x[MakeSmallMap-13]
	_ = x[MakeLargeMap-14]
	_ = x[MakeSet-15]
	_ = x[DefValue-16]
	_ = x[DefValue3-17]
	_ = x[Def-18]
	_ = x[Def3-19]
	_ = x[SetMeta-20]
	_ = x[Call-21]
	_ = x[Apply-22]
	_ = x[MethodCall-23]
	_ = x[Throw-24]
	_ = x[PushHandler-25]
	_ = x[PopHandler-26]
	_ = x[CheckType-27]
	_ = x[SetLocal-28]
	_ = x[GetLocal-29]
	_ = x[Return-30]
	_ = x[CheckArityFixed-31]
	_ = x[CheckArityMin-32]
	_ = x[ThrowArity-33]
	_ = x[MakeFn-34]
	_ = x[RefUpval-35]
	_ = x[PushSelfFn-36]
	_ = x[SetLabel-37]
	_ = x[SetLine-38]
}

const _OpCode_name = "NoopPopDupJumpJumpIfTrueJumpIfFalseResolveVarSetMacroGetBindingGetUpvalSetUpvalPushLiteralMakeVectorMakeSmallMapMakeLargeMapMakeSetDefValueDefValue3DefDef3SetMetaCallApplyMethodCallThrowPushHandlerPopHandlerCheckTypeSetLocalGetLocalReturnCheckArityFixedCheckArityMinThrowArityMakeFnRefUpvalPushSelfFnSetLabelSetLine"

var _OpCode_index = [...]uint16{0, 4, 7, 10, 14, 24, 35, 45, 53, 63, 71, 79, 90, 100, 112, 124, 131, 139, 148, 151, 155, 162, 166, 171, 181, 186, 197, 207, 216, 224, 232, 238, 253, 266, 276, 282, 290, 300, 308, 315}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
