// This file is generated by generate-std.clj script. Do not edit manually!


package yaml

import (
	. "github.com/lab47/lace/core"
	"fmt"
	"os"
)

func InternsOrThunks(env *Env, ns *Namespace) {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of yaml.InternsOrThunks().")
	}
	ns.ResetMeta(MakeMeta(nil, `Implements encoding and decoding of YAML.`, "1.0"))

	
	ns.InternVar(env, "read-string", read_string_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("s"))),
			`Parses the YAML-encoded data and return the result as a Joker value.`, "1.0"))

	ns.InternVar(env, "write-string", write_string_,
		MakeMeta(
			NewListFrom(NewVectorFrom(MakeSymbol("v"))),
			`Returns the YAML encoding of v.`, "1.0"))

}
