// This file is generated by generate-std.clj script. Do not edit manually!

//go:build fast_init
// +build fast_init

package html

import (
	"fmt"
	. "github.com/lab47/lace/core"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running fast version of html.InternsOrThunks().")
	}
	STD_thunk_html_escape__var = __escape_
	STD_thunk_html_unescape__var = __unescape_
}
