// This file is generated by generate-std.clj script. Do not edit manually!

package uuid

import (
	. "github.com/lab47/lace/core"
)


var __new__P ProcFn = __new_
var new_ Proc = Proc{Fn: __new__P, Name: "new_", Package: "std/uuid"}

func __new_(_env *Env, _args []Object) (Object, error) {
	_c := len(_args)
	switch {
	case _c == 0:
		var err error
		_res, err := new()
		return MakeString(_res), err

	default:
		return nil, ErrorArity(_env, _c)
	}
}

func Init(env *Env, ns *Namespace) {

	InternsOrThunks(env, ns)
}

func init() {
	AddNativeNamespace("uuid", func(env *Env) error {
		ns := env.EnsureNamespace(MakeSymbol("lace.uuid"))
		Init(env, ns)
		return nil
	})
}
