// This file is generated by generate-std.clj script. Do not edit manually!

package uuid

import (
	"fmt"
	"os"

	. "github.com/lab47/lace/core"
)

func InternsOrThunks(env *Env, ns *Namespace) {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of uuid.InternsOrThunks().")
	}
	ns.ResetMeta(MakeMeta(nil, `Generates UUIDs.`, "1.0"))

	ns.InternVar(env, "new", new_,
		MakeMeta(
			NewListFrom(NewVectorFrom()),
			`Creates a new random UUID.`, "1.0").Plus(env, MakeKeyword("tag"), MakeString("String")))

}
